[package]
name = "AptosKYC"
version = "1.0.0"
authors = ["Cognifyr"]

[addresses]
kyc = "_"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "testnet"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.AptosToken]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "testnet"
subdir = "aptos-move/framework/aptos-token"

[dev-dependencies]
